Adding Verbosity to table reader
deangelisdf/write2audiobook pull request #19
Opened 2024-09-17 05:29 UTC by Krishn1412

Added a verbose parameter, sugar texts and logging statements

2024-09-19 10:46 UTC, deangelisdf requested changes

2024-09-21 11:55 UTC, deangelisdf requested changes
Please check conflict with last mai commit and please try the script. 
Could you please check the references to language parameter?

2024-09-23 09:34 UTC, Krishn1412 commented
> Please check conflict with last mai commit and please try the script. Could you please check the references to language parameter?

Could you explain the second part? Where should I check the reference for language parameter?

2024-09-26 19:04 UTC, deangelisdf commented on docx2audio.py
> +    'it-IT': {
```suggestion
    'it': {
```

2024-09-26 19:04 UTC, deangelisdf commented on docx2audio.py
> +                          language="it-IT", verbose = False) -> Tuple[str, str]:
```suggestion
                          language=LANGUAGE, verbose = False) -> Tuple[str, str]:
```

2024-09-26 19:06 UTC, deangelisdf commented on docx2audio.py
> +            if verbose:
Could you please move this code in `get_text_from_table`?

2024-09-26 19:07 UTC, deangelisdf requested changes
Please look the comments. I add some comments, some little update is already applied

2025-05-04 19:11 UTC, closed without merging